= Gender Detection API
Kamran Abbaszade;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

[[overview_model_dto]]
== Model DTO Classes

For implementation of gender detection algorithms three model classes were designed.

=== RequestDto

Model POJO class representing the JSON object provided in Http Post request to `"/request"` endpoint.

|===
| Modifier and Type | Field and Description

| String
| `name` - Used to hold name for further evaluation through algorithms of gender detection
|===

=== ResourceDto

Model POJO class representing the JSON object retrieved from Http Get request to `"/resource"` endpoint.

|===
| Modifier and Type | Field and Description

| List<String>
| `listOfMaleNames` - Used to keep list of male names

| List<String>
| `listOfFemaleNames` - Used to keep list of female names
|===

=== ResponseDto

Model POJO class representing the JSON object retrieved from Http Post request to `"/request"` endpoint.

|===
| Modifier and Type | Field and Description

| String
| `firstAlgorithmResult` - Used to keep results of analysing name using first algorithm, when only first token is checked

| String
| `secondAlgorithmResult` - Used to keep results of analysing name using second algorithm, when all token are checked. 
If frequency of male name`s occurance is more than for female names, then result is Male, oppositly - Female. In case of equal frequency - INCONCLUSIVE
|===

[[overview_util]]
== Utility classes

In order to evaluate the fastest manipulations with Flat Text Files two utils classes were 
created. They are: *FileResourcesUtils* and *ResourceReaderUtils*.

=== FileResourcesUtils

Util class designed to read Resources directory of root source as a stream and convert it into InputStream Object.

|===
| Modifier and Type | Method and Description

| InputStream
| `getFileFromResourceAsStream(String fileName)` - Used to get File from Resource folder as stream
|===

==== Method Detail

java.io.InputStream *getFileFromResourceAsStream(String fileName)*

*Parameters:* fileName - name of the File.

*Returns:* reference to InputStream Object of file.

=== ResourceReaderUtils

Util abstract class designed to read InputStream Object using BufferedReader and convert it 
into String LinkedList object.

|===
| Modifier and Type | Method and Description

| List<String>
| `bufferedResourceReaderToList(String fileName)` - Used to read file and convert it into List of Strings
|===

==== Method Detail

List<String> *bufferedResourceReaderToList(String fileName)*

*Parameters:* fileName - name of the File.

*Returns:* reference to List of Strings Object represented as LinkedList.

[[overview_algorithm]]
== Algorithm implementation

In order to implement gender detection algorithms a GenderDetectionAlgorithm interface and 
GenderDetectionAlgorithmImpl class were created.

=== GenderDetectionAlgorithm

An interface with declared method designed to be implemented for gender detection.

|===
| Modifier and Type | Method and Description

| org.java.model.ResponseDto
| `detectGender(RequestDto requestDto)` - Can be used to detect gender by name
|===

==== Method Detail

org.java.model.ResponseDto *detectGender(RequestDto requestDto)*

*Parameters:* requestDto - RequestDto object.

*Returns:* reference to ResponseDto object, with results of passing name through two algorithms.

=== GenderDetectionAlgorithmImpl

An implementation of GenderDetectionAlgorithm interface with overriden method detectGender() 
and two private methods used to desribe two algorithms of gender detection.

|===
| Modifier and Type | Method and Description

| org.java.model.ResponseDto
| `detectGender(RequestDto requestDto)` - Used to detect gender by name and construct ResponseDto object.
|===

==== Method Detail

org.java.model.ResponseDto *detectGender(RequestDto requestDto)*

*Parameters:* requestDto - RequestDto object.

*Returns:* reference to ResponseDto object, with results of passing name through two algorithms.

[[overview_service]]
== Service Layer

The service layer of application invokes corresponding implementation of util and algorithm classes. 

Service Layer consist of a GenderDetectionService interface with two declared methods and 
a GenderDetectionServiceImpl class with implementation of predeclared methods.

=== GenderDetectionService

An interface with declared methods designed to be implemented for invoking gender detection algorithms 
and retrieving existing list of male and female names respectively.

|===
| Modifier and Type | Method and Description

| org.java.model.ResourceDto
| `getListOfNames()` - Can be used to invoke utility objects to read existing list of male and female names and wrap into ResourceDto object

| org.java.model.ResponseDto
| `detectGender(RequestDto requestDto)` - Can be used to invoke gender detection algorithms and pass results to requester
|===

==== Method Detail

org.java.model.ResourceDto *getListOfNames()*

*Parameters:* no parameters needed

*Returns:* reference to ResourceDto object, which wrapes the List of male and female names.

'''

org.java.model.ResponseDto *detectGender(RequestDto requestDto)*

*Parameters:* requestDto - RequestDto object.

*Returns:* reference to ResponseDto object, with results of passing name through two algorithms.

=== GenderDetectionServiceImpl

An implementation of GenderDetectionService interface with declared methods designed for invoking gender detection algorithms 
and retrieving existing list of male and female names respectively.

|===
| Modifier and Type | Method and Description

| org.java.model.ResourceDto
| `getListOfNames()` - Used to invoke utility objects to read existing list of male and female names and wrap into ResourceDto object

| org.java.model.ResponseDto
| `detectGender(RequestDto requestDto)` - Used to invoke gender detection algorithms and pass results to requester
|===

==== Method Detail

org.java.model.ResourceDto *getListOfNames()*

*Parameters:* no parameters needed

*Returns:* reference to ResourceDto object, which wrapes the List of male and female names.

'''

org.java.model.ResponseDto *detectGender(RequestDto requestDto)*

*Parameters:* requestDto - RequestDto object.

*Returns:* reference to ResponseDto object, with results of passing name through two algorithms.

[[overview_controller]]
== Controller Layer

The Controller layer of application designed to accept Http requests sent to two endpoints: `*"/resource"*` and `*"/request"*`.
The corresponding service layer methods are invoke when HTTP Get request with no arguments is sent to `*"/resource"*` endpoint
and when HTTP Post request with JSON file in body representing RequestDto object is sent to `*"/request"*`.

=== GenderDetectionController

Controller class with two methods defined in order to invoke service object`s methods and pass results to Http Client

=== JSON file example for HTTP POST request
====

----
{
    "name": "OLIVER JACK"
}
----

====


|===
| Modifier and Type | Method and Description

| org.java.model.ResourceDto
| `getListOfNames()` - Used to invoke service object which executes org.java.service.GenderDetectionServiceImpl#getListOfNames()

| org.java.model.ResponseDto
| `detectGender(RequestDto requestDto)` - Used to invoke service object which executes org.java.service.GenderDetectionServiceImpl#detectGender(RequestDto requestDto)
|===

==== Method Detail

org.java.model.ResourceDto *getListOfNames()*

*Parameters:* no parameters needed

*Returns:* reference to ResourceDto object, which wrapes the List of male and female names.

'''

org.java.model.ResponseDto *detectGender(RequestDto requestDto)*

*Parameters:* requestDto - RequestDto object.

*Returns:* reference to ResponseDto object, with results of passing name through two algorithms.

[[overview_controller]]
== List of Gradle Dependencies

++++

dependencies {
    //START Spring
    implementation 'org.springframework.boot:spring-boot-starter-web'
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
    //END Spring

    //START Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    //END Lombok

    //START Additional Dependencies
    testCompile group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.3'
    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.7.0'
    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0'
    testCompile group: 'org.spockframework', name: 'spock-core', version: '1.3-groovy-2.5'
    testCompile platform("org.spockframework:spock-bom:2.0-M4-groovy-3.0")
    compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '3.0.7', ext: 'pom'
    compile 'org.springframework.restdocs:spring-restdocs-asciidoctor'
    //END Additional Dependencies

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: "com.vaadin.external.google", module:"android-json"
    }
}

++++